# Generated by Django 4.2 on 2025-09-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_remove_employee_user'),
        ('validationlists', '0002_alter_validationlists_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationlists',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validationlist_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='validationlists',
            name='listvalue',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='validationlists',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validationlist_updated', to='Employee.employee'),
        ),
    ]
