# Generated by Django 5.2.5 on 2025-08-29 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userrole_created_userrole_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
