# Generated by Django 5.2.5 on 2025-08-29 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userrole_created_alter_userrole_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role_priority',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'SuperAdmin')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
