# Generated by Django 5.2.5 on 2025-08-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_userrole_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
