# Generated by Django 5.2.5 on 2025-08-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('Users', '0005_remove_userrole_role_remove_userrole_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_updated', to='Employee.employee'),
        ),
    ]
