# Generated by Django 5.2.5 on 2025-08-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_userrole_createdby_alter_userrole_updatedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='is_deleted',
        ),
    ]
