# Generated by Django 5.2.5 on 2025-08-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_userrole_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
