# Generated by Django 5.2.5 on 2025-08-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_userrole_createdby_alter_userrole_updatedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='created_emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
