# Generated by Django 4.2 on 2025-09-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('Users', '0010_userrole_created_emp_id_userrole_updated_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='permissions.permission'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
