# Generated by Django 4.2 on 2025-09-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_userrole_can_create_userrole_can_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='can_view',
            new_name='can_export',
        ),
    ]
