# Generated by Django 4.2 on 2025-09-08 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_rename_can_view_userrole_can_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
