# Generated by Django 5.2.5 on 2025-09-01 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialType', '0002_alter_materialtype_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='materialtype',
            name='created_emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='updated_emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialtype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialtype_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
