# Generated by Django 5.2.5 on 2025-09-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialType', '0003_remove_materialtype_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='created_emp_id',
        ),
        migrations.RemoveField(
            model_name='materialtype',
            name='updated_emp_id',
        ),
        migrations.AddField(
            model_name='materialtype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
