# Generated by Django 5.2.5 on 2025-09-01 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('MaterialType', '0004_remove_materialtype_created_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialtype_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialtype_updated', to='Employee.employee'),
        ),
    ]
