# Generated by Django 5.2.5 on 2025-08-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailDomain', '0002_remove_emaildomain_description'),
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildomain',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emaildomain_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='emaildomain',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emaildomain_updated', to='Employee.employee'),
        ),
    ]
