# Generated by Django 5.2.5 on 2025-08-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supergroups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatGroup',
            fields=[
                ('mgrp_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('is_service', models.BooleanField(default=False)),
                ('mgrp_shortname', models.CharField(max_length=150)),
                ('mgrp_longname', models.CharField(max_length=150)),
                ('attribgrpid', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgroup_created', to=settings.AUTH_USER_MODEL)),
                ('sgrp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matgroups', to='supergroups.supergroup')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgroup_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
