# Generated by Django 4.2 on 2025-09-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matg_attributes', '0003_alter_matgattribute_createdby_and_more'),
        ('matgroups', '0003_alter_matgroup_createdby_alter_matgroup_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matgroup',
            name='attribgrpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgroups', to='matg_attributes.matgattribute'),
        ),
    ]
