# Generated by Django 4.2 on 2025-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0004_alter_matgroup_attribgrpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matgroup',
            name='attribgrpid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
