# Generated by Django 4.2 on 2025-09-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0005_alter_matgroup_attribgrpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matgroup',
            name='mgrp_longname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='matgroup',
            name='mgrp_shortname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
