# Generated by Django 4.2 on 2025-09-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supergroups', '0003_alter_supergroup_createdby_and_more'),
        ('matgroups', '0006_alter_matgroup_mgrp_longname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matgroup',
            name='sgrp_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matgroups', to='supergroups.supergroup'),
        ),
    ]
