# Generated by Django 4.2 on 2025-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0007_alter_matgroup_sgrp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matgroup',
            name='mgrp_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
