# Generated by Django 5.2.5 on 2025-08-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_updated'),
        ('Users', '0005_remove_userrole_role_remove_userrole_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='Users.userrole'),
        ),
    ]
