# Generated by Django 5.2.5 on 2025-08-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_company_updated'),
        ('Employee', '0004_employee_password_alter_employee_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Company.company'),
        ),
    ]
