# Generated by Django 5.2.5 on 2025-08-30 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_company_updated'),
        ('Employee', '0005_alter_employee_company_name'),
        ('Users', '0005_remove_userrole_role_remove_userrole_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('emp_name',), name='unique_active_employee_name'),
        ),
    ]
