# Generated by Django 5.2.5 on 2025-09-01 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_company_updated'),
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('Users', '0010_userrole_created_emp_id_userrole_updated_emp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_active_employee_email'),
        ),
    ]
