# Generated by Django 4.2 on 2025-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_alter_employee_email_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
