# Generated by Django 4.2 on 2025-09-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_employee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to='Employee.employee'),
        ),
    ]
