# Generated by Django 4.2 on 2025-09-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_alter_employee_createdby_alter_employee_updatedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
