# Generated by Django 4.2 on 2025-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0016_employee_email_otp_employee_email_otp_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
