# Generated by Django 4.2 on 2025-09-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0017_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_otp_created',
        ),
    ]
