# Generated by Django 5.2.5 on 2025-08-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('local_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sap_item_id', models.IntegerField(blank=True, help_text='Number assigned by SAP', null=True)),
                ('mat_type_code', models.CharField(max_length=4)),
                ('mgrp_code', models.CharField(max_length=9)),
                ('item_desc', models.CharField(max_length=40)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('search_text', models.CharField(blank=True, help_text='Concatenated searchable text', max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemmaster_created', to=settings.AUTH_USER_MODEL)),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemmaster_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
