# Generated by Django 5.2.5 on 2025-08-31 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_alter_itemmaster_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemmaster_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemmaster_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
