# Generated by Django 5.2.5 on 2025-09-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('itemmaster', '0003_alter_itemmaster_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemmaster_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='sap_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='search_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemmaster_updated', to='Employee.employee'),
        ),
    ]
