# Generated by Django 4.2 on 2025-09-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0003_alter_matgroup_createdby_alter_matgroup_updatedby'),
        ('MaterialType', '0005_alter_materialtype_createdby_and_more'),
        ('itemmaster', '0004_alter_itemmaster_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='mat_type_code',
            field=models.ForeignKey(db_column='mat_type_code', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MaterialType.materialtype'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='mgrp_code',
            field=models.ForeignKey(db_column='mgrp_code', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='matgroups.matgroup'),
        ),
    ]
