# Generated by Django 5.2.5 on 2025-08-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperGroup',
            fields=[
                ('sgrp_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('sgrp_name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supergroup_created', to=settings.AUTH_USER_MODEL)),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supergroup_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
