# Generated by Django 5.2.5 on 2025-08-29 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supergroup',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supergroup',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
