# Generated by Django 5.2.5 on 2025-09-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('supergroups', '0002_alter_supergroup_created_alter_supergroup_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supergroup',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supergroup_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='supergroup',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supergroup_updated', to='Employee.employee'),
        ),
    ]
