# Generated by Django 5.2.5 on 2025-08-29 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemmaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_status', models.CharField(choices=[('open', 'Open'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=10)),
                ('user_text', models.CharField(blank=True, max_length=200)),
                ('reply_text', models.CharField(blank=True, max_length=200)),
                ('reply_emaildate', models.DateTimeField(blank=True, null=True)),
                ('reply_smsdate', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('closetime', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('timetaken', models.IntegerField(blank=True, help_text='Time taken in seconds to get ITEM ID', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_created', to=settings.AUTH_USER_MODEL)),
                ('sap_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.itemmaster')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
