# Generated by Django 5.2.5 on 2025-09-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('requests', '0002_alter_request_createdby_alter_request_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='timetaken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_updated', to='Employee.employee'),
        ),
    ]
