# Generated by Django 4.2 on 2025-09-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_createdby_alter_project_project_code_and_more'),
        ('requests', '0003_alter_request_createdby_alter_request_timetaken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
