# Generated by Django 4.2 on 2025-09-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reply_text',
            field=models.JSONField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_text',
            field=models.JSONField(blank=True, max_length=200),
        ),
    ]
