# Generated by Django 4.2 on 2025-09-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_request_reply_text_alter_request_user_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='project_id',
            new_name='project_code',
        ),
        migrations.AlterField(
            model_name='request',
            name='reply_text',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_text',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
