# Generated by Django 4.2 on 2025-09-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_rename_project_id_request_project_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='reply_text',
            new_name='text_message',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_text',
        ),
    ]
