# Generated by Django 4.2 on 2025-09-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_rename_reply_text_request_text_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='text_message',
        ),
        migrations.AddField(
            model_name='request',
            name='messages',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
