# Generated by Django 4.2 on 2025-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_remove_request_text_message_request_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
