# Generated by Django 5.2.5 on 2025-09-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuprequest',
            old_name='created',
            new_name='submitted_at',
        ),
    ]
