# Generated by Django 5.2.5 on 2025-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_requests', '0002_rename_created_signuprequest_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuprequest',
            old_name='submitted_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
