# Generated by Django 4.2 on 2025-09-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_company_updated'),
        ('signup_requests', '0004_alter_signuprequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_requests', to='Company.company'),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='emp_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
