# Generated by Django 5.2.5 on 2025-09-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvals', '0001_initial'),
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('signup_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='submitted_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='description',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='email',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='approval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee'),
        ),
        migrations.AddField(
            model_name='approval',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='role_assigned',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Mdgt', 'Mdgt'), ('User', 'User')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='signup_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='signup_requests.signuprequest'),
        ),
        migrations.AddField(
            model_name='approval',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
