# Generated by Django 5.2.5 on 2025-09-01 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvals', '0002_rename_submitted_at_approval_created_and_more'),
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
