# Generated by Django 5.2.5 on 2025-09-01 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvals', '0003_approval_employee_alter_approval_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='employee',
        ),
        migrations.AlterField(
            model_name='approval',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
