# Generated by Django 5.2.5 on 2025-09-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvals', '0004_remove_approval_approved_by_remove_approval_employee_and_more'),
        ('signup_requests', '0004_alter_signuprequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='role_assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='signup_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='signup_requests.signuprequest'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
