# Generated by Django 5.2.5 on 2025-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvals', '0005_alter_approval_created_alter_approval_role_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='username',
        ),
        migrations.AddField(
            model_name='approval',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
