# Generated by Django 5.2.5 on 2025-09-02 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approvals', '0006_remove_approval_username_approval_email'),
        ('Company', '0002_alter_company_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='Company.company'),
        ),
    ]
