# Generated by Django 5.2.5 on 2025-08-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matgroups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatgAttribute',
            fields=[
                ('attrib_id', models.AutoField(primary_key=True, serialize=False)),
                ('attrib_printpriority', models.IntegerField(default=0, help_text='Lower value appears earlier in item name')),
                ('attrib_name', models.CharField(max_length=30)),
                ('attrib_printname', models.CharField(max_length=10)),
                ('attrib_name_validation', models.CharField(blank=True, max_length=30)),
                ('att_maxnamelen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attrib_tagname', models.CharField(max_length=10)),
                ('attrib_tag_validation', models.CharField(blank=True, max_length=30)),
                ('attrib_maxtaglen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgattr_created', to=settings.AUTH_USER_MODEL)),
                ('mgrp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='matgroups.matgroup')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgattr_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
