# Generated by Django 5.2.5 on 2025-09-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_user_alter_employee_createdby_and_more'),
        ('matg_attributes', '0002_alter_matgattribute_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matgattribute',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgattr_created', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='matgattribute',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgattr_updated', to='Employee.employee'),
        ),
    ]
